FROM accetto/ubuntu-vnc-xfce-chromium-g3

USER root

ARG NODE_MAJOR=20

RUN apt-get update \
    && apt-get install -y curl git \
    supervisor \
    python-is-python3 \
    && curl -LsSf https://astral.sh/uv/install.sh | sh \
    && rm -rf /var/lib/apt/lists/*

# 载入下面安装的uv工具和uv tool工具的使用
ENV PATH="/home/headless/.local/bin:${PATH}"

WORKDIR /app

# RUN chown -R headless:headless /app
# COPY --chown=headless:headless . .

COPY . .

RUN cp -r /app/. /home/headless/app && cd /home/headless/app \
    && uv tool install mcp-proxy \
    && uv tool install 'browser-use[cli]' \
    && uv tool install playwright \
    && playwright install --with-deps chromium

# Install WebUI(browser-use) 
# RUN git clone --depth 1 -b v2.0.0 https://github.com/browser-use/web-ui.git /home/headless/web-ui \
#     && cd /home/headless/web-ui && uv venv && uv pip install -r requirements.txt

# Install Node.js using NodeSource PPA
RUN mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && curl -LsSf https://astral.sh/uv/install.sh | sh \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && apt-get update \
    && apt-get install nodejs -y \
    && rm -rf /var/lib/apt/lists/*

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/dockerstartup/startup.sh"]
